### ISSUE TITLE
Needs An Actual Looping Example With Characters

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/phase-3-control-flow-loops#9]
### Canvas Link

https://learning.flatironschool.com/courses/5286/assignments/172601?module_item_id=376619

### Concern

This lab needs a better example that actually shows how to iterate through characters of a string in Ruby for the 'reverse_string' function.

**Comment by lizbur10** [comment]
Hi there,

Thank you for your feedback! The Phase 3 content is currently in the process of being updated, so we will take this information into consideration as we proceed.

As always, thanks for contributing! 💙
